local:
  cmos:
    host: 'localhost'
    user: 'app-t1c'
    password: 'Zxcv123!'
    db: 'DBMKP'
  fms:
    host: 'localhost'
    port: 5433
    user: 'postgres'
    password: 'Zxcv123!autopos'
    db: 'dbfms'
  ftp:
    host: 'ai-upload.central.tech'
    user: 'autopos.cds-uat'
    is_enable: false
  # format = YYYYMMDD
  run_date:
  #format = YYYYMMDDHHmm
  birbs_date:
  #format = YYYYMMDDHHmmss
  bissp_date:
staging:
  cmos:
    host: 'localhost'
    user: 'app-t1c'
    password: 'Zxcv123!'
    db: 'DBMKP'
  fms:
    host: 'rbs-fms-staging.chcyqkx1lpmh.ap-southeast-1.rds.amazonaws.com'
    port: 5432
    user: 'postgres'
    password: 'Zxcv123!autopos'
    db: 'dbfms'
  ftp:
    host: 'ai-upload.central.tech'
    user: 'autopos.cds-uat'
    is_enable: true
  run_date:
  birbs_date:
  bissp_date:
prod:
  cmos:
    host: 'localhost'
    user: 'app-t1c'
    password: 'Zxcv123!'
    db: 'DBMKP'
  fms:
    host: 'localhost'
    port: 5432
    user: 'postgres'
    password: 'Zxcv123!autopos'
    db: 'dbfms'
  ftp:
    host: 'ai-upload.central.tech'
    user: 'autopos.cds-prod'
    is_enable: true
  run_date:
  birbs_date:
  bissp_date: